#+TITLE:      Ledger en Emacs para finanzas
#+AUTHOR:     jero98772 , son0p
#+EMAIL:      
#+INFOJS_OPT: view:t toc:t ltoc:t mouse:underline buttons:0 path:http://thomasf.github.io/solarized-css/org-info.min.js
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://thomasf.github.io/solarized-css/solarized-dark.min.css" />
#+OPTIONS:    H:3 num:nil toc:t \n:nil ::t |:t ^:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE:   es
#+PRIORITIES: A C B
#+CATEGORY:   communication
#+CONSTANTS: pi=3.14159265358979323846
#+STYLE: <link rel="stylesheet" type="text/css" href="slides.css" />

** Ledger-mode
*** Anatomía de una transacción
    #+BEGIN_SRC ledger
         2021/04/05 Paga factura A25  Ochoa  
           banco:0609                                      $ 402,189
           ingreso:comprobante:20                          $ 402,189 
           ; compIngreso: No. 20
           ;
           ; EMPRESA: A38 S.A.S.   NIT: 10142101 
           ; CIUDAD: Medellin
           ; 
           ; ctaOrigen: 
           ; ctaDestino: 31100000696
           ;
           ; PAGADOR: Electrostatica Ochoa 
           ; NIT: 101301711
           ;
           ; EN LETRAS: Cuatroscientos dos mil ciento
           ;            ochenta y nueve pesos m/l
           ;
           ;
           ; RETEFUENTE: $103,096 (3.5%)
           ;
           ;
           ingreso:arriendo:bodega:A25     $ 402,189
           cxc:arriendo:bodega:A25         $-402,189
           ; fact: A25
           ; bod: 113

    #+END_SRC
**** Fecha, beneficiarios, cuentas, monedas, cantidades    
**** Metadatos y comentarios
     Se usará el punto y coma ``` ; ``` para los comentarios y metadata
     
     Se usará la forma la forma ``` ; categoria: valor ``` para asignar diferentes valores a una misma categoria, ejemplo: el metadato ``` ; to: elvis ``` le asignara el valor ```elvis``` a la categoría ``` to: ```
     
**** Balance en cada transacción
**** Verificar (reporte)
*** Moverse y editar con el teclado
    M-p (previous) va a la transacción anterior
    M-n (next) va a la transacción siguiente
    M-f (forward) va a la siguiente palabra
    M-b (back) va a la palabra anterior
    C-f (forward) va al caracter siguiente
    C-b (back) va al caracter anterior
    C-a salta al inicio de la línea
    C-e (end) salta al final de la línea
    M-d (delete) borra la palabra a la derecha
    C-k (kill) borra desde la posición hasta el final de la línea
    C-/ undo
    


** ¿Qué es [[https://www.gnu.org/software/emacs/][Emacs]]?
*** Emacs es un editor de texto , muy completo y muy personalizable. 
** ¿Para qué ?
*** Emacs esta hecha para optimisar tiempo al momento de escribir , al cambiar de teclado a mouse se pierde mucho tiempo , emacs es una herramienta para usar lo minimo el mouse y manipular el editor mediente atajos de teclado.
*** Emacs es una herramienta que sirve para todo por su adptabilidad y la facilidad de solucionar de nesesidades , cosas como finanzas , programar , documentar  escribir ... etc ...
*** es para introducir los datos
** ¿Qué es Ledger?
*** un sistema de contabilidad de doble entrada , con caracteristicas minimalisatas ,muy manipulable , maneja varias divisas y es una herramienta para operar fechas  
** ¿Para que?
*** es una herramienta para manejar datos, nesesitamos una herramienta para manejarlos para que nos permita observar cosas que no son tan faciles de ver , evitando hacer calculos repetitivos que quitan tiempo .
*** es buena opcion en cosas como: un registro con un miles de datos que para leerlos y operarlos se nesesitan años , ledger lo lee y hace los calculos nesarios en segundos . 
<<<<<<< HEAD

=======
>>>>>>> fa3bc08d9ec3fcd1b7dc456d6af25c68182d7620

** introduccion a Ledger-Mode
*** para activarlo de modo manual use:
**** M-x ledger-mode
**** alt-x ledger-mode
*** los archivos de ledger son los que terminan en .ledger
** referencias d e ledger-mode
*** videos
**** https://www.youtube.com/watch?v=GUuWgk3dXd0&list=PLkjnQ3NFTPnY1eNyLDGi547gkVui1vyn2&index=2 , de emacsconf
**** https://www.youtube.com/watch?v=cjoCNRpLanY
**** https://www.youtube.com/watch?v=FJtaM43PgXQ
**** https://www.youtube.com/watch?v=0aFeonG4wWk
