#+TITLE:      Ledger en Emacs para finanzas
#+AUTHOR:     son0p,jero98772
#+EMAIL:      
#+INFOJS_OPT: view:t toc:t ltoc:t mouse:underline buttons:0 path:http://thomasf.github.io/solarized-css/org-info.min.js
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://thomasf.github.io/solarized-css/solarized-dark.min.css" />
#+OPTIONS:    H:3 num:nil toc:t \n:nil ::t |:t ^:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE:   es
#+PRIORITIES: A C B
#+CATEGORY:   communication
#+CONSTANTS: pi=3.14159265358979323846
#+STYLE: <link rel="stylesheet" type="text/css" href="slides.css" />

** Ledger-mode
*** Anatomía de una transacción
    #+BEGIN_SRC ledger
         2021/04/05 Paga factura A25  Ochoa  
           banco:0609                                      $ 402,189
           ingreso:comprobante:20                          $ 402,189 
           ; compIngreso: No. 20
           ;
           ; EMPRESA: A38 S.A.S.   NIT: 10142101 
           ; CIUDAD: Medellin
           ; 
           ; ctaOrigen: 
           ; ctaDestino: 31100000696
           ;
           ; PAGADOR: Electrostatica Ochoa 
           ; NIT: 101301711
           ;
           ; EN LETRAS: Cuatroscientos dos mil ciento
           ;            ochenta y nueve pesos m/l
           ;
           ;
           ; RETEFUENTE: $103,096 (3.5%)
           ;
           ;
           ingreso:arriendo:bodega:A25     $ 402,189
           cxc:arriendo:bodega:A25         $-402,189
           ; fact: A25
           ; bod: 113

    #+END_SRC
**** Conceptos :Fecha, beneficiarios, cuentas, monedas, cantidades
***** Fecha
      Ledger usa la forma AAAA-MM-DD, por convención usaremos las fechas separadas por barra AAAA/MM/DD
****** Ledger mode permite programar cronologicamente transacciones , permite programar las siguientes transacciones en fechas específicas y unidades de fecha como  dias ,semanas ,meses...
****** Para programarlo en fechas use [año,mes,dia] , Ejemplo: programar los dias 1 y 15 del mes 
  #+BEGIN_SRC ledger
  [*/*/1,15] Transaccion
  #+END_SRC
****** Para programarlo en unidades de fecha
***** Cuentas (categorías)
      La cuenta =ingreso:arriendo:bodega= será entendida como una cuenta ingreso que tiene una sub-cuenta llamada arriendo que a su vez tiene una sub-cuenta bodega.
***** Monedas
      Podemos usar diferentes especies:  $, EUR, COP, h, m, s. por convención usaremos el separador =,= para miles y =.= para centavos
**** Metadatos y comentarios
     Se usará el punto y coma =;= para los comentarios y metadata
     
     Se usará la forma =; categoria: valor= para asignar diferentes valores a una misma categoria, ejemplo: el metadato =; to: elvis= le asignara el valor =elvis= a la categoría =to:=
     
**** Balance en cada transacción
**** Verificar (reporte)
     Para verificar que el registro cumpla los requerimientos de Ledger podemos invocar el reporte balance (bal) usando =C-c-o-r= 
** Conceptos 

*** Moverse y editar con el teclado
#+BEGIN_SRC 
    M-p (previous) va a la transacción anterior
    M-n (next) va a la transacción siguiente
    M-f (forward) va a la siguiente palabra
    M-b (back) va a la palabra anterior
    C-f (forward) va al caracter siguiente
    C-b (back) va al caracter anterior
    C-a salta al inicio de la línea
    C-e (end) salta al final de la línea
    M-d (delete) borra la palabra a la derecha
    C-k (kill) borra desde la posición hasta el final de la línea
    C-/ undo
    C-c-o-r (reporte)
#+END_SRC    
    

** ¿Qué es [[https://www.gnu.org/software/emacs/][Emacs]]?
*** Emacs es un editor de texto , muy completo y muy personalizable. 
** ¿Para qué ?
*** Emacs esta hecho para optimizar tiempo al momento de escribir , al cambiar de teclado a mouse se pierde mucho tiempo , emacs es una herramienta para usar lo mínimo el mouse y manipular el editor mediente atajos de teclado.
*** Emacs es una herramienta que sirve para todo por su adptabilidad y la facilidad de solucionar de necesidades , cosas como finanzas , programar , documentar,  escribir ... etc ...
*** Es para introducir los datos
** ¿Qué es [[[https://www.ledger-cli.org/][Ledger]]]?
*** Un sistema de contabilidad de doble entrada , con características minimalistas, muy manipulable, maneja varias divisas y es una herramienta para operar fechas  
** ¿Para qué?
*** Es una herramienta para manejar datos, necesitamos una herramienta para manejarlos para que nos permita observar cosas que no son tan fáciles de ver , evitando hacer calculos repetitivos que quitan tiempo.
*** Es buena opción en cosas como: un registro con miles de datos que para leerlos y operarlos se nesesitan años, ledger lo lee y hace los cálculos necesarios en segundos . 


** Introduccion a Ledger-Mode
*** Para activarlo de modo manual use:
**** M-x ledger-mode
**** alt-x ledger-mode
*** Los archivos de ledger acostumbran terminar en .ledger o .ldg
** Referencias a ledger-mode
*** Videos
**** https://www.youtube.com/watch?v=g0TcEedJ-js , de emacsconf
**** https://www.youtube.com/watch?v=cjoCNRpLanY
**** https://www.youtube.com/watch?v=FJtaM43PgXQ
**** https://www.youtube.com/watch?v=0aFeonG4wWk
*** Enlaces de foros
**** https://groups.google.com/g/ledger-cli/c/MZwjYEp2rjU
